DjangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from DjangoBlog.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap
from DjangoBlog.feeds import DjangoBlogFeed
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static
from DjangoBlog.admin_site import admin_site
from django.urls import include, path

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'
urlpatterns = [
                  url(r'^admin/', admin_site.urls),
                  url(r'', include('blog.urls', namespace='blog')),
                  url(r'mdeditor/', include('mdeditor.urls')),
                  url(r'', include('comments.urls', namespace='comment')),
                  url(r'', include('accounts.urls', namespace='account')),
                  url(r'', include('oauth.urls', namespace='oauth')),
                  url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
                      name='django.contrib.sitemaps.views.sitemap'),
                  url(r'^feed/$', DjangoBlogFeed()),
                  url(r'^rss/$', DjangoBlogFeed()),
                  url(r'^search', include('haystack.urls'), name='search'),
                  url(r'', include('servermanager.urls', namespace='servermanager')),
                  url(r'', include('owntracks.urls', namespace='owntracks'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.urls import path

from . import views as v

app_name = 'base'

urlpatterns = [
    # path('404/', v.miss_page, name='miss-page'),
    # path('portfolio-2/', v.portfolio_2, name='blog-post'),
    # path('portfolio-2/', v.portfolio_2, name='portfolio-2'),
    # path('portfolio-3/', v.portfolio_3, name='portfolio-3'),
    # path('pricing-tables/', v.pricing_tables, name='pricing-tables'),
    # path('shortcodes/', v.shortcodes, name='shortcodes'),
    # path('single-project/', v.single_project, name='single-project'),
    # path('text-columns/', v.text_columns, name='text-columns'),
]

blog/urls.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: urls.py
@time: 2016/11/2 下午7:15
"""

from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = "blog"
urlpatterns = [
    path(r'', views.IndexView.as_view(), name='index'),
    path(r'page/<int:page>/', views.IndexView.as_view(), name='index_page'),

    path(r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
         views.ArticleDetailView.as_view(),
         name='detailbyid'),

    path('case', views.CaseListView.as_view(), name='case'),
    path('case/<int:pk>', views.CaseDetailView.as_view(), name='case-detail'),

    path(r'category/<slug:category_name>.html', views.CategoryDetailView.as_view(), name='category_detail'),
    path(r'category/<slug:category_name>/<int:page>.html', views.CategoryDetailView.as_view(),
         name='category_detail_page'),

    path(r'author/<author_name>.html', views.AuthorDetailView.as_view(), name='author_detail'),
    path(r'author/<author_name>/<int:page>.html', views.AuthorDetailView.as_view(),
         name='author_detail_page'),

    path(r'tag/<slug:tag_name>.html', views.TagDetailView.as_view(), name='tag_detail'),
    path(r'tag/<slug:tag_name>/<int:page>.html', views.TagDetailView.as_view(), name='tag_detail_page'),
    path('archives.html', cache_page(60 * 60)(views.ArchivesView.as_view()), name='archives'),
    path('links.html', views.LinkListView.as_view(), name='links'),
    path(r'upload', views.fileupload, name='upload'),
    path(r'refresh', views.refresh_memcache, name='refresh')

]

case/urls.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: urls.py
@time: 2016/11/2 下午7:15
"""
from django.conf.urls import url
from django.urls import path
from django.views.decorators.cache import cache_page

from website.utils import my_cache
from . import views
from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import SearchView
from . import views as v

app_name = "case"
urlpatterns = [
    url(r'(?P<category_pk>[0-9]+)/(?P<case_pk>[0-9]+)$', my_cache(v.CaseDetailView.as_view), name='case-detail'),
    url(r'(?P<category_pk>[0-9]+)$', my_cache(v.CategoryDetailView.as_view), name='category-detail'),

]

website/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from base.views import collection_message
from website.admin_site import admin_site
from website.feeds import DjangoBlogFeed
from website.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'base.views.page_not_found_view'
handler500 = 'base.views.server_error_view'
handle403 = 'base.views.permission_denied_view'

app_name = 'website'

urlpatterns = [

                  # 首页
                  url(r'', include('home.urls', namespace='home')),
                  # 关于
                  url(r'^about/', include('about.urls', namespace='about')),
                  # 服务
                  url(r'^service/', include('service.urls', namespace='service')),
                  # 产品
                  url(r'^product/', include('product.urls', namespace='product')),
                  # 案例
                  url(r'^case/', include('case.urls', namespace='case')),
                  # 留言
                  url(r'^message/', collection_message, name='message'),
                  # 移动端
                  url(r'^mobile/', include('mobile.urls', namespace='mobile')),
                  # 博客
                  url(r'^blog/', include('blog.urls', namespace='blog')),

                  url(r'', include('comments.urls', namespace='comment')),
                  url(r'', include('accounts.urls', namespace='account')),
                  url(r'', include('oauth.urls', namespace='oauth')),
                  url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
                      name='django.contrib.sitemaps.views.sitemap'),
                  url(r'^feed/$', DjangoBlogFeed()),
                  url(r'^rss/$', DjangoBlogFeed()),
                  url(r'^search', include('haystack.urls'), name='search'),
                  url(r'', include('servermanager.urls', namespace='servermanager')),
                  url(r'', include('owntracks.urls', namespace='owntracks')),
                  # 富文本编辑器
                  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
                  # url(r'^ckeditor5/', include('django_ckeditor_5.urls')),
                  # md文档编辑器
                  url(r'^mdeditor/', include('mdeditor.urls')),
                  # 管理端
                  url(r'^admin/', admin_site.urls),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                      # For django versions before 2.0:
                      # url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

blog/models.py
import logging
from abc import ABCMeta, abstractmethod, abstractproperty

from django.db import models
from django.urls import reverse
from django.conf import settings
from uuslug import slugify

from website.utils import get_current_site
from website.utils import cache_decorator, cache
from django.utils.timezone import now
from mdeditor.fields import MDTextField

logger = logging.getLogger(__name__)

LINK_SHOW_TYPE = (
    ('i', '首页'),
    ('l', '列表页'),
    ('p', '文章页面'),
    ('a', '全站'),
    ('s', '友情链接页面'),
)


class BaseModel(models.Model):
    id = models.AutoField(primary_key=True)
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)

    def save(self, *args, **kwargs):
        is_update_views = isinstance(self, Article) and 'update_fields' in kwargs and kwargs['update_fields'] == [
            'views']
        if is_update_views:
            Article.objects.filter(pk=self.pk).update(views=self.views)
        else:
            if 'slug' in self.__dict__:
                slug = getattr(self, 'title') if 'title' in self.__dict__ else getattr(self, 'name')
                setattr(self, 'slug', slugify(slug))
            super().save(*args, **kwargs)

    def get_full_url(self):
        site = get_current_site().domain
        url = "https://{site}{path}".format(site=site, path=self.get_absolute_url())
        return url

    class Meta:
        abstract = True

    @abstractmethod
    def get_absolute_url(self):
        pass


class Article(BaseModel):
    """文章"""
    STATUS_CHOICES = (
        ('d', '草稿'),
        ('p', '发表'),
    )
    COMMENT_STATUS = (
        ('o', '打开'),
        ('c', '关闭'),
    )
    TYPE = (
        ('a', '文章'),
        ('p', '页面'),
    )
    title = models.CharField('标题', max_length=200, unique=True)
    body = MDTextField('正文')
    pub_time = models.DateTimeField('发布时间', blank=False, null=False, default=now)
    status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICES, default='p')
    comment_status = models.CharField('评论状态', max_length=1, choices=COMMENT_STATUS, default='o')
    reference_url = models.URLField('引用地址', max_length=200, null=True, blank=True)
    type = models.CharField('类型', max_length=1, choices=TYPE, default='a')
    views = models.PositiveIntegerField('浏览量', default=0)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', blank=True, null=True,
                               on_delete=models.CASCADE)
    article_order = models.IntegerField('排序,数字越大越靠前', blank=False, null=False, default=0)
    category = models.ForeignKey('Category', verbose_name='分类', on_delete=models.CASCADE, blank=False, null=False)
    tags = models.ManyToManyField('Tag', verbose_name='标签集合', blank=True)
    objects = models.Manager()

    def body_to_string(self):
        return self.body

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-article_order', '-pub_time']
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        get_latest_by = 'id'

    def get_absolute_url(self):
        return reverse('blog:detailbyid', kwargs={
            'article_id': self.id,
            'year': self.created_time.year,
            'month': self.created_time.month,
            'day': self.created_time.day
        })

    @cache_decorator(60 * 60 * 10)
    def get_category_tree(self):
        tree = self.category.get_category_tree()
        names = list(map(lambda c: (c.name, c.get_absolute_url()), tree))

        return names

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def viewed(self):
        self.views += 1
        self.save(update_fields=['views'])

    def comment_list(self):
        cache_key = 'article_comments_{id}'.format(id=self.id)
        value = cache.get(cache_key)
        if value:
            logger.info('get article comments:{id}'.format(id=self.id))
            return value
        else:
            comments = self.comment_set.filter(is_enable=True)
            cache.set(cache_key, comments, 60 * 100)
            logger.info('set article comments:{id}'.format(id=self.id))
            return comments

    def get_admin_url(self):
        info = (self._meta.app_label, self._meta.model_name)
        return reverse('admin:%s_%s_change' % info, args=(self.pk,))

    @cache_decorator(expiration=60 * 100)
    def next_article(self):
        # 下一篇
        return Article.objects.filter(id__gt=self.id, status='p').order_by('id').first()

    @cache_decorator(expiration=60 * 100)
    def prev_article(self):
        # 前一篇
        return Article.objects.filter(id__lt=self.id, status='p').first()


class Category(BaseModel):
    """文章分类"""
    name = models.CharField('分类名', max_length=30, unique=True)
    parent_category = models.ForeignKey('self', verbose_name="父级分类", blank=True, null=True, on_delete=models.CASCADE)
    slug = models.SlugField(default='no-slug', max_length=60, blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = "分类"
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        return reverse('blog:category_detail', kwargs={'category_name': self.slug})

    def __str__(self):
        return self.name

    @cache_decorator(60 * 60 * 10)
    def get_category_tree(self):
        """
        递归获得分类目录的父级
        :return: 
        """
        categorys = []

        def parse(category):
            categorys.append(category)
            if category.parent_category:
                parse(category.parent_category)

        parse(self)
        return categorys

    @cache_decorator(60 * 60 * 10)
    def get_sub_categorys(self):
        """
        获得当前分类目录所有子集
        :return: 
        """
        categorys = []
        all_categorys = Category.objects.all()

        def parse(category):
            if category not in categorys:
                categorys.append(category)
            childs = all_categorys.filter(parent_category=category)
            for child in childs:
                if category not in categorys:
                    categorys.append(child)
                parse(child)

        parse(self)
        return categorys


class Tag(BaseModel):
    """文章标签"""
    name = models.CharField('标签名', max_length=30, unique=True)
    slug = models.SlugField(default='no-slug', max_length=60, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag_detail', kwargs={'tag_name': self.slug})

    @cache_decorator(60 * 60 * 10)
    def get_article_count(self):
        return Article.objects.filter(tags__name=self.name).distinct().count()

    class Meta:
        ordering = ['name']
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Links(models.Model):
    """友情链接"""

    name = models.CharField('链接名称', max_length=30, unique=True)
    link = models.URLField('链接地址')
    sequence = models.IntegerField('排序', unique=True)
    is_enable = models.BooleanField('是否显示', default=True, blank=False, null=False)
    show_type = models.CharField('显示类型', max_length=1, choices=LINK_SHOW_TYPE, default='i')
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)

    class Meta:
        ordering = ['sequence']
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SideBar(models.Model):
    """侧边栏,可以展示一些html内容"""
    name = models.CharField('标题', max_length=100)
    content = models.TextField("内容")
    sequence = models.IntegerField('排序', unique=True)
    is_enable = models.BooleanField('是否启用', default=True)
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)

    class Meta:
        ordering = ['sequence']
        verbose_name = '侧边栏'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

case/views.py
from django.urls import reverse
from django.views.generic import ListView, DetailView
from case.models import Case, Category


# class CaseListView(ListView):
#     # template_name = 'home/project_index.html'
#     model = Case
#     ordering = ('sequence',)
#
#     def get_context_data(self, **kwargs):
#         # pk = int(self.kwargs[self.pk_url_kwarg])
#         return super().get_context_data(**kwargs)


class CategoryDetailView(DetailView):
    # 分类
    model = Category
    pk_url_kwarg = 'category_pk'

    # 分类 和 案例列表
    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all()
        category_pk = int(self.kwargs['category_pk'])
        kwargs['case_list'] = Case.objects.filter(category=category_pk).all()
        return super().get_context_data(**kwargs)


class CaseDetailView(DetailView):
    # 案例详情
    model = Case
    pk_url_kwarg = 'case_pk'

    def get_context_data(self, **kwargs):
        # pk = int(self.kwargs[self.pk_url_kwarg])
        kwargs['category_list'] = Category.objects.all()
        kwargs['next_case'] = self.object.next_case
        kwargs['prev_case'] = self.object.prev_case
        kwargs['related_cases'] = self.object.get_related_cases
        return super().get_context_data(**kwargs)

case/templates/case/case_detail.html
{% extends 'share_layout/home_layout.html' %}
{% load static %}
{% block content %}

    {% comment %}    <style type="text/css">
        #nav_menus {
            position: fixed;
            left: 200px;
            width: 260px;
            bottom-: 500px;
        }
    </style>{% endcomment %}
    <!--楼盘展示-->
    <div class="display clearfix">
        <div class="container">
            <div class="account-l fl fixed_nav" id="nav_menus">
                <div class="case_left_t">
                    <div class="list-title">
                        <a>外包案例</a>
                        <span>Cases</span>
                    </div>
                    <ul id="accordion" class="accordion">
                        <!--只有一级产品分类-->
                        <!--<li><a href="gallery.php?cid=34"><div class="link">管理系统系列</div></a></li><li><a href="gallery.php?cid=35"><div class="link">网站建设系列</div></a></li><li><a href="gallery.php?cid=43"><div class="link">APP软件系列</div></a></li><li><a href="gallery.php?cid=44"><div class="link">桌面软件系列</div></a></li><li><a href="gallery.php?cid=45"><div class="link">物联网系列</div></a></li>-->

                        <!--点击一级分类出现二级分类-->
                        {% for s in category_list %}
                            <li><a href="{% url 'case:category-detail' category_pk=s.id %}">
                                <div class="link">{{ s.name }}</div>
                            </a></li>
                        {% endfor %}
                    </ul>
                </div>
                {% include 'includes/contact.html' %}
            </div>

            <div class="display_show fr">
                <div class="common_title clearfix">
                    <div class="loft fl">
                        {# <img src="{% static 'images/fz.png' %}"> #} 外包案例
                    </div>
                    <div class="more fr">
                        您当前位置：<a href="{% url 'home:index' %}">网站首页</a> > <a
                            href="{{ case.category.get_absolute_url }}">{{ case.category.name }}</a> > {{ case.name }}
                    </div>
                </div>
                <div class="gangwan">
                    <h3>{{ case.name }}</h3>
                    <div class="gangwan_top clearfix">
                        <div class="gangwan_top_l fl">
                            <a href="{{ case.prev_case.get_absolute_url }}">
                                <img src="{% static 'images/show_l.png' %}">
                            </a>
                        </div>
                        <div class="gangwan_top_m fl">
                            <a href="javascript:void(0);">
                                <img src="{{ case.thumb.url }}" width="464px"
                                     height="348">
                            </a>
                        </div>
                        <div class="gangwan_top_r fl">
                            <a href="{{ case.next_case.get_absolute_url }}">
                                <img src="{% static 'images/show_r.png' %}">
                            </a>
                        </div>
                    </div>
                </div>
                <div class="detail_top">
                    <h3>详情介绍</h3>
                    <div class="detail">
                        {{ case.content| safe }}
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

case/templates/case/category_detail.html
{% extends 'share_layout/home_layout.html' %}
{% load static %}

{% block content %}

    {% comment %}    <style type="text/css">
        #nav_menus {
            position: fixed;
            left: 200px;
            width: 260px;
            bottom-: 500px;
        }
    </style>{% endcomment %}
    <!--楼盘展示-->
    <div class="display clearfix">
        <div class="container">
            <div class="account-l fl fixed_nav" id="nav_menus">
                <div class="case_left_t">
                    <div class="list-title">
                        <a>外包案例</a>
                        <span>Cases</span>
                    </div>
                    <ul id="accordion" class="accordion">
                        <!--只有一级产品分类-->
                        <!--<li><a href="gallery.php?cid=34"><div class="link">管理系统系列</div></a></li><li><a href="gallery.php?cid=35"><div class="link">网站建设系列</div></a></li><li><a href="gallery.php?cid=43"><div class="link">APP软件系列</div></a></li><li><a href="gallery.php?cid=44"><div class="link">桌面软件系列</div></a></li><li><a href="gallery.php?cid=45"><div class="link">物联网系列</div></a></li>-->

                        <!--点击一级分类出现二级分类-->
                        {% for s in category_list %}
                            <li><a href="{% url 'case:category-detail' category_pk=s.id %}">
                                <div class="link">{{ s.name }}</div>
                            </a></li>
                        {% endfor %}
                    </ul>
                </div>
                {% include 'includes/contact.html' %}
            </div>


            <div class="display_show fr">
                <div class="common_title clearfix">
                    <div class="loft fl">
                        {# <img src="{% static 'images/fz.png' %}"> #} {{ category.name }}
                    </div>
                    {#                    <div class="more fr">#}
                    {#                        您当前位置：<a href="index.php.html">网站首页</a> > 外包案例#}
                    {#                    </div>#}
                </div>
                <div class="product_show clearfix">
                    <ul class="clearfix">

                        {% for case in case_list %}
                            <li>
                                {#                                <a href="{% url 'case:case-detail' category_pk=category.id case_pk=case.id %}">#}
                                <a href="{{ case.get_absolute_url }}">
                                    <div class="p_show_img">
                                        <img src="{{ case.thumb.url }}">
                                    </div>
                                    <div class="p_show_title clearfix">
                                        <div class="pt_one fl">
                                            <h3>{{ case.name }}</h3>
                                        </div>
                                        <div class="pt_two fr">
                                            <img src="{% static 'images/y_hongse.png' %}">
                                        </div>
                                    </div>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

            </div>
        </div>

    </div>

{% endblock %}