DjangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from DjangoBlog.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap
from DjangoBlog.feeds import DjangoBlogFeed
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static
from DjangoBlog.admin_site import admin_site
from django.urls import include, path

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'
urlpatterns = [
                  url(r'^admin/', admin_site.urls),
                  url(r'', include('blog.urls', namespace='blog')),
                  url(r'mdeditor/', include('mdeditor.urls')),
                  url(r'', include('comments.urls', namespace='comment')),
                  url(r'', include('accounts.urls', namespace='account')),
                  url(r'', include('oauth.urls', namespace='oauth')),
                  url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
                      name='django.contrib.sitemaps.views.sitemap'),
                  url(r'^feed/$', DjangoBlogFeed()),
                  url(r'^rss/$', DjangoBlogFeed()),
                  url(r'^search', include('haystack.urls'), name='search'),
                  url(r'', include('servermanager.urls', namespace='servermanager')),
                  url(r'', include('owntracks.urls', namespace='owntracks'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.urls import path

from . import views as v

app_name = 'base'

urlpatterns = [
    # path('404/', v.miss_page, name='miss-page'),
    # path('portfolio-2/', v.portfolio_2, name='blog-post'),
    # path('portfolio-2/', v.portfolio_2, name='portfolio-2'),
    # path('portfolio-3/', v.portfolio_3, name='portfolio-3'),
    # path('pricing-tables/', v.pricing_tables, name='pricing-tables'),
    # path('shortcodes/', v.shortcodes, name='shortcodes'),
    # path('single-project/', v.single_project, name='single-project'),
    # path('text-columns/', v.text_columns, name='text-columns'),
]

mobile/urls.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: urls.py
@time: 2016/11/2 下午7:15
"""

from django.urls import path
from django.views.decorators.cache import cache_page

from website.utils import my_cache
from . import views as v

app_name = "mobile"
urlpatterns = [
    path('service', my_cache(v.ServiceListView.as_view), name='service'),
    path('service/<int:pk>', my_cache(v.ServiceDetailView.as_view), name='service-detail'),
    path('product', my_cache(v.ProductListView.as_view), name='product'),
    path('product/<int:pk>', my_cache(v.ProductDetailView.as_view), name='product-detail'),
    path('category/<int:category_pk>', my_cache(v.CategoryDetailView.as_view), name='category'),
    path('case', my_cache(v.CaseListView.as_view), name='case'),
    path('case/<int:pk>', my_cache(v.CaseDetailView.as_view), name='case-detail'),
    path('about/<int:pk>', my_cache(v.AboutDetailView.as_view), name='about'),
    # path('', v.index,  name='index'),
]

website/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from base.views import collection_message
from website.admin_site import admin_site
from website.feeds import DjangoBlogFeed
from website.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'base.views.page_not_found_view'
handler500 = 'base.views.server_error_view'
handle403 = 'base.views.permission_denied_view'

app_name = 'website'

urlpatterns = [

                  # 首页
                  url(r'', include('home.urls', namespace='home')),
                  # 关于
                  url(r'^about/', include('about.urls', namespace='about')),
                  # 服务
                  url(r'^service/', include('service.urls', namespace='service')),
                  # 产品
                  url(r'^product/', include('product.urls', namespace='product')),
                  # 案例
                  url(r'^case/', include('case.urls', namespace='case')),
                  # 留言
                  url(r'^message/', collection_message, name='message'),
                  # 移动端
                  url(r'^mobile/', include('mobile.urls', namespace='mobile')),
                  # 博客
                  url(r'^blog/', include('blog.urls', namespace='blog')),

                  url(r'', include('comments.urls', namespace='comment')),
                  url(r'', include('accounts.urls', namespace='account')),
                  url(r'', include('oauth.urls', namespace='oauth')),
                  url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
                      name='django.contrib.sitemaps.views.sitemap'),
                  url(r'^feed/$', DjangoBlogFeed()),
                  url(r'^rss/$', DjangoBlogFeed()),
                  url(r'^search', include('haystack.urls'), name='search'),
                  url(r'', include('servermanager.urls', namespace='servermanager')),
                  url(r'', include('owntracks.urls', namespace='owntracks')),
                  # 富文本编辑器
                  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
                  # url(r'^ckeditor5/', include('django_ckeditor_5.urls')),
                  # md文档编辑器
                  url(r'^mdeditor/', include('mdeditor.urls')),
                  # 管理端
                  url(r'^admin/', admin_site.urls),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                      # For django versions before 2.0:
                      # url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

mobile/models.py
from django.db import models

# Create your models here.

mobile/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import DetailView, ListView

from about.models import AboutItem
from blog.views import LinkListView
from case.models import Category, Case
from home.models import Home
from product.models import Product
from service.models import Service


class ServiceListView(ListView):
    template_name = 'mobile/service/service_list.html'
    model = Service


class ServiceDetailView(DetailView):
    template_name = 'mobile/service/service_detail.html'
    model = Service


class ProductListView(ListView):
    template_name = 'mobile/product/product_list.html'
    model = Product


class ProductDetailView(DetailView):
    template_name = 'mobile/product/product_detail.html'
    model = Product


class CategoryDetailView(DetailView):
    template_name = 'mobile/case/case_list.html'
    model = Category
    pk_url_kwarg = 'category_pk'

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all()
        category_pk = int(self.kwargs['category_pk'])
        kwargs['case_list'] = Case.objects.filter(category=category_pk).all()
        return super().get_context_data(**kwargs)


class CaseListView(ListView):
    template_name = 'mobile/case/case_list.html'
    model = Case

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all()
        return super().get_context_data(**kwargs)


class CaseDetailView(DetailView):
    template_name = 'mobile/case/case_detail.html'
    model = Case

    def get_context_data(self, **kwargs):
        # pk = int(self.kwargs[self.pk_url_kwarg])
        kwargs['next_case'] = self.object.next_case
        kwargs['prev_case'] = self.object.prev_case
        kwargs['related_cases'] = self.object.get_related_cases
        return super().get_context_data(**kwargs)


class AboutDetailView(DetailView):
    template_name = 'mobile/about/about_detail.html'
    model = AboutItem

    def get_context_data(self, **kwargs):
        kwargs['about_list'] = AboutItem.objects.all()
        return super().get_context_data(**kwargs)

mobile/templates/mobile/index.html
{% extends 'share_layout/mobile_layout.html' %}

{% block content %}
    <div class="swipe">
        <ul id="slider">
            {% for c in carousel_list %}
                <li><img src="{{ c.image.url }}"/></li>
            {% endfor %}
        </ul>
        <div id="pagenavi">
            {% for c in carousel_list %}
                {% if forloop.counter == 1 %}
                    <a href="javascript:void(0);" class="active">{{ forloop.counter }}</a>
                {% else %}
                    <a href="javascript:void(0);">{{ forloop.counter }}</a>
                {% endif %}
            {% endfor %}
        </div>
    </div>


    <div class="clear"></div>


    <div class="clear"></div>
    <div class="product">
        <div class="index_t"><span class="fl">外包案例</span><a href="{% url 'mobile:case' %}" class="fr nav_pro">更多&gt;&gt;</a></div>
        <ul style=" padding-top:8px;">
            {% for s in case_list %}
                <li>
                    <a href="{{ s.get_mobile_url }}">
                        <div class="picbox">
                            <img src="{{ s.thumb.url }}" onload="autoimg()" class="imgauto"/>
                        </div>
                        <p style="color:#fff;" class="pictitle">{{ s.name }}</p>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="clear"></div>
    <div class="">
        <div class="index_t"><span class="fl">公司产品</span><a href="{% url 'mobile:product' %}" class="fr nav_pro">更多&gt;&gt;</a></div>
        <ul style=" padding-top:8px;">
            {% for s in product_list %}
                <li>
                    <a href="{{ s.get_mobile_url }}">
                        <div class="picbox">
                            <img src="{{ s.thumb.url }}" onload="autoimg()" class="imgauto"/>
                        </div>
                        <p style="color:#fff;" class="pictitle">{{ s.name }}</p>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="clear"></div>
   {% comment %} <div class="">
        <div class="index_t"><span class="fl">服务项目</span><a href="{% url 'mobile:service' %}" class="fr nav_pro">更多&gt;&gt;</a></div>

        <ul style=" padding-top:8px;">
            {% for s in service_list %}
                <li>
                    <a href="{{ s.get_mobile_url }}">
                        <div class="picbox">
                            <img src="{{ s.thumb.url }}" onload="autoimg()" class="imgauto"/>
                        </div>
                        <p style="color:#fff;" class="pictitle">{{ s.name }}</p>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="clear"></div>{% endcomment %}
    <div class="">
        <div class="index_t"><span class="fl">服务项目</span><a href="{% url 'mobile:service' %}" class="fr nav_pro">更多&gt;&gt;</a>
        </div>
        <ul class="newsmain">
            {% for s in service_list %}
                <li>
                    <a href="{{ s.get_mobile_url }}">{{ s.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="clear"></div>
    <div class="about">

        <div class="index_t"><span class="fl">关于我们</span><a href="{% url 'mobile:about' pk=1 %}" class="fr nav_pro">更多&gt;&gt;</a></div>

        <ul>
            <li style=" line-height:30px; padding:10px;">
                <p style="text-indent:2em; ">
                    {{ home.about_description }}
                </p></li>
        </ul>
    </div>
    <div class="clear"></div>
{% endblock %}